spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/E_COMMERCE?createDatabaseIfNotExist=true&useSSL=true
    username: root
    password: 27701
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true
  