spring:
  datasource:
    url: jdbc:mysql://localhost:3306/E_COMMERCE?createDatabaseIfNotExist=true
    username: root
    password: 27701
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true
server:
  port: 5000