spring:
  datasource:
    url: jdbc:mysql://ecommercedb.c0lrqwuyarga.eu-west-3.rds.amazonaws.com:3306/E_COMMERCE?createDatabaseIfNotExist=true
    username: root
    password: nassardev
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true
server:
  port: 5000