export const categories = [
    { value: 31,  label: "Men Fashion"   },
    { value: 32,  label: "Women Fashion"   },
    { value: 33,  label: "Phone & Accessories"   },
    { value: 34,  label: "Computer, Office & Security"   },
    { value: 35,  label: "Jewelry & Warches"   },
    { value: 36,  label: "Bags & Shoes"   },
    { value: 37,  label: "Toys & Kids"   },
    { value: 38,  label: "Sporting Goods"   },
    { value: 39,  label: "Health"   },
    { value: 40,  label: "Beauty & Hair"   },
    { value: 41,  label: "Software"   },
    { value: 42,  label: "Home Improvement"   },
    { value: 43,  label: "Art"   },
    { value: 44,  label: "Hand Made"   },
    { value: 45,  label: "Books"   },
    { value: 46,  label: "School Supplies"   },
    { value: 47,  label: "Camera"   },
    { value: 48,  label: "Travel"   },
]